### ISSUE TITLE
Won't launch after recent update

### ISSUE THREAD

**Issue by thedaemon** [ghostbsd/station-tweak#7]
No matter how I try to run it it crashes.
 This is from .xsession-errors:
`(station-tweak:2582): Gtk-WARNING **: 18:05:47.916: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Traceback (most recent call last):
  File "/usr/local/bin/station-tweak", line 449, in <module>
    StationTweak()
  File "/usr/local/bin/station-tweak", line 309, in __init__
    img = theme.load_icon(sidePage.icon, 36, 0)
GLib.Error: rsvg-error-quark: Failed to load /usr/local/share/icons/Vivacious-Colors/apps/scalable/preferences-system-windows.svg: XML parse error: error code=201 (3) in (null):10:53: Namespace prefix sodipodi for docname on svg is not defined
 (0)`

and this is from running from the console:
`thedaemon> station-tweak

(station-tweak:2693): Gtk-WARNING **: 18:06:52.604: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Traceback (most recent call last):
  File "/usr/local/bin/station-tweak", line 449, in <module>
    StationTweak()
  File "/usr/local/bin/station-tweak", line 309, in __init__
    img = theme.load_icon(sidePage.icon, 36, 0)
GLib.Error: rsvg-error-quark: Failed to load /usr/local/share/icons/Vivacious-Colors/apps/scalable/preferences-system-windows.svg: XML parse error: error code=201 (3) in (null):10:53: Namespace prefix sodipodi for docname on svg is not defined
 (0)`

**Comment by thedaemon** [comment]
New updated with icons fixed this issue.
